[build]
image = "ubuntu:22.04"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3 python3-pip python3-venv",
    "ln -s /usr/bin/python3 /usr/bin/python",
    "ln -s /usr/bin/pip3 /usr/bin/pip"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind=0.0.0.0:$PORT"
